### ISSUE TITLE
The endpoint did not accept the request. (Code: 500)

### ISSUE THREAD

**Issue by eventhorizonpl** [checkout/checkout-sdk-php#30] opened 2019-07-03 14:48 UTC
Hi,

I'm trying to update a just created webhook and I'm getting
`
In HttpHandler.php line 327:

  [Checkout\Library\Exceptions\CheckoutHttpException (500)]
  The endpoint did not accept the request. (Code: 500)

Exception trace:
 () at /home/michal/projects/somtel-api/vendor/checkout/checkout-sdk-php/src/Library/HttpHandler.php:327
 Checkout\Library\HttpHandler->handleError() at /home/michal/projects/somtel-api/vendor/checkout/checkout-sdk-php/src/Library/HttpHandler.php:296
 Checkout\Library\HttpHandler->execute() at /home/michal/projects/somtel-api/vendor/checkout/checkout-sdk-php/src/Library/Controller.php:93
 Checkout\Library\Controller->response() at /home/michal/projects/somtel-api/vendor/checkout/checkout-sdk-php/src/Controllers/WebhookController.php:147
 Checkout\Controllers\WebhookController->update() at /home/michal/projects/somtel-api/src/RemitBundle/Service/CheckoutComService.php:112

`

Here is a code that I use
`
    public function webhooksUpdate(string $id, string $url): Webhook
    {
        $webhook = new Webhook($url, $id);

        return $this->checkoutApi->webhooks()->update($webhook);
    }
`

Best regards,
Michal

**Comment by aquila-freitas-cko** [comment] 2019-07-04 08:39
It seems to be something with the Gateway. I will look into this but it's very likely that I won't be able to help.

**Comment by eventhorizonpl** [comment] 2019-07-04 08:57
@aquila-freitas-cko 
Ok, no problem if you will not be able to help with that. My project manager should provide me a direct contact to the support.

**Comment by aquila-freitas-cko** [comment] 2019-07-04 11:15
Hey @eventhorizonpl , the issue is not on the SDK, therefore I am not able to help you here. I will close this issue.

**Closed by aquila-freitas-cko** 2019-07-04 11:15 UTC
